### ISSUE TITLE
Enhancement Request - Create Bill Connect if not exists

### ISSUE THREAD

**Issue by bryankaraffa** [flexera-public/cbi-oi-kubecost-exporter#43]
Currently the exporter requires the bill connect already to exist, if it doesn't exist the exporter fails.  This requirement introduces challenges for deploying the exporter to a dynamic number of kubecost deployments.

If we added functionality to the exporter to [create the cbi-oi-kubecost bill connect](https://developer.flexera.com/docs/api/finops-onboarding/v1#/Bill%20Connect%20-%20Common%20Bill%20Ingestion/Bill%20Connect%20-%20Common%20Bill%20Ingestion%23create) if it does not exist, that would enable teams to more easily onboard costs into platform for new clusters.

It could be disabled by default to maintain parity with previous behavior (fail if not exist), but can be enabled with a flag or env variable for scenarios were we know the bill connect will not exist and we want the exporter to create it instead of erroring.  This is typical of non-Federated implementations and clusters are created/destroyed often using Infrastructure as Code or some other automated release process.

**Comment by Kaaku2302** [comment]
> Currently the exporter requires the bill connect already to exist, if it doesn't exist the exporter fails. This requirement introduces challenges for deploying the exporter to a dynamic number of kubecost deployments.
> 
> If we added functionality to the exporter to [create the cbi-oi-kubecost bill connect](https://developer.flexera.com/docs/api/finops-onboarding/v1#/Bill%20Connect%20-%20Common%20Bill%20Ingestion/Bill%20Connect%20-%20Common%20Bill%20Ingestion%23create) if it does not exist, that would enable teams to more easily onboard costs into platform for new clusters.
> 
> It could be disabled by default to maintain parity with previous behavior (fail if not exist), but can be enabled with a flag or env variable for scenarios were we know the bill connect will not exist and we want the exporter to create it instead of erroring. This is typical of non-Federated implementations and clusters are created/destroyed often using Infrastructure as Code or some other automated release process.

The issue has been addressed with this PR:
https://github.com/flexera-public/cbi-oi-kubecost-exporter/pull/46
The following version of helm chart has the fix.
https://github.com/flexera-public/cbi-oi-kubecost-exporter/blob/main/helm-chart/cbi-oi-kubecost-exporter-1.16.0.tgz

Two additional parameters have been added

1. CREATE_BILL_CONNECT_IF_NOT_EXIST - Flag to enable automatic creation of Bill Connect. Default is false.
2. VENDOR_NAME - Vendor name for the Bill Connect. It is used when CREATE_BILL_CONNECT_IF_NOT_EXIST is set to true . Default value is "Kubecost".

flexera.createBillConnectIfNotExist
flexera.vendorName
Thank you.
